Repository algosup/2023-2024-project-4-sportshield-team-2, pull requests merged in 2024-03, with the labels that each got.

#33 Documents
  Documents/Communication/03_18_2024_meetingSummary.md
  Documents/Functional/Img/ALGOSUP-logo.png
  Documents/Functional/Img/Coris-innovation-logo.png
  Documents/Functional/Img/proto_scheme.png
  Documents/Functional/Img/proto_scheme_bottom.png
  Documents/Functional/functionalSpecifications.md
  Documents/TestPlan/testPlan.md
  Documents/UserManual/Img/BluetoothSettings.png
  Documents/UserManual/Img/BluetoothSettingsFunctionnalities.png
  Documents/UserManual/Img/BluetoothUnlock.png
  Documents/UserManual/Img/cableHolderAndExit.png
  Documents/UserManual/Img/chargingPort.png
  Documents/UserManual/Img/device.png
  Documents/UserManual/Img/deviceBottom.png
  Documents/UserManual/Img/findBluetooth.jpg
  Documents/UserManual/userManual.md
  Documents/UserManual/userManual.pdf
  Documents/testPlan.md
Labels: documentation, enhancement

#34 Fixing missing images in the functional
  Documents/Functional/Img/ashley_ricks.png
  Documents/Functional/Img/steve_sinclair.png
  Documents/Functional/Img/william_greener.png
  Documents/UserManual/userManual.md
  Documents/UserManual/userManual.pdf
Labels: documentation, enhancement, invalid

#81 GitHub Actions for the main branch
  .github/workflows/actions.yml
  .gitignore
  Src/batteryControl.ino
  test/src/tests.cpp
Labels: enhancement, high, unit-test

#82 Update actions.yml
  .github/workflows/actions.yml
Labels: enhancement, high, unit-test
